server {
    listen 80 default_server;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass         https://tennisstats.be/api/;
        proxy_set_header   Host tennisstats.be;
        proxy_ssl_server_name on;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    server_name ~^www\.(?<domain>.+)$;
    return 301 https://$domain$request_uri;
}
